trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: OAFootwears-Variables

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
              addToPath: true
          - script: npm ci
            displayName: 'Install dependencies'
          - script: npm run build
            displayName: 'Build the project'
          - script: npm run test
            displayName: 'Run tests'
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(Build.SourcesDirectory)'
              includeRootFolder: false
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
            artifact: drop

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        steps:
          - download: current
            artifact: drop
          - task: AzureWebApp@1
            inputs:
              azureSubscription: 'AzureRM Connection'
              appName: 'ASP-oafootwears-995f'
              resourceGroupName: '(New) Resource group'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|18-lts'
              startUpCommand: 'npm start'