import "./globals.css";

import { Analytics } from "@vercel/analytics/react"

import RenderNav from "@/components/Navbar/RenderNav";
import MainFoot from "@/components/MainFoot";

export const metadata = {
  title: "O & A Footwears",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`h-screen mx-auto bg-primary/5 text- font-body`}
      >
        <RenderNav />
        {children}
        <MainFoot />
        <Analytics />
      </body>
    </html>
  );
}
