import "./globals.css";


export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-500 justify-center`}>
        {children}
      </body>
    </html>
  );
}
