import "./globals.css";


export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`mx-10 css-selector min-h-screen font-primary`}>
        {children}
      </body>
    </html>
  );
}
